config/routes.rb
Rails.application.routes.draw do
  resources :bugs, except: [:edit]
  resources :projects
  devise_for :users, except: [:edit]
  
  root 'static_pages#home'
  get '/users', to: 'static_pages#home'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project

  validates :title, presence:true
  validates :description, presence:true

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :bugs
  
  validates :name,  presence: true, length: { maximum: 50 }
  validates :project_manager, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 300 }
  validates :date_create, presence: true
  validates :area, presence: true
  validates :state, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence:true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  

  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :passwordl])
      end

end

app/controllers/bugs_controller.rb
require 'slack.rb'
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  include SlackCommunication 
  # GET /bugs
  # GET /bugs.json
  
  

  def index
    @bugs = Bug.order(:solved).all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
        BugsHelper.sendMessage("Bug in the project *#{@bug.project.name}*:\n>>> _#{@bug.title}_ - #{@bug.description}", current_user.name)
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to bugs_url, notice: 'Bug was successfully fixed.' }
        format.json { render :show, status: :ok, location: @bug }
        BugsHelper.sendMessage("Bug _'#{@bug.title}'_ in the project *#{@bug.project.name}* was fixed.", current_user.name)
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :solved, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :project_manager, :description, :date_create, :date_finished, :area, :state)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  
  def full_title(page_title = '')
    base_title = "Inventos Digitais Challenge"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/bugs_helper.rb
require 'slack-notifier'	

module BugsHelper
  
	CHANNEL = "https://hooks.slack.com/services/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"
	#CHANNEL ="https://hooks.slack.com/services/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"
	def BugsHelper.sendMessage(text, userName)
		notifier = Slack::Notifier.new CHANNEL
		notifier.ping(text, username: userName, icon_emoji: ':japanese_goblin:')
	end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bugs/_form.html.slim
= semantic_form_for @bug do |f| 
  - unless @bug.errors.empty? 
    = render 'layouts/error_signup_messages', object: @bug

  = f.inputs do 
    .form-group
      = f.input :project, :input_html => {:autocomplete => "off", :class => "form-control"}
    .form-group
      = f.input :title,  :input_html => {:autofocus => true, :class => "form-control" } 
    .form-group
      = f.input :description, :input_html => {:autocomplete => "off", :class => "form-control"} 

  = f.actions do 
    = f.action :submit, :as => :input, :label => "Report", :button_html => { :disable_with => t(:wait), :class => "btn btn-danger btn-block" } 

app/views/bugs/index.html.slim
div class="jumbotron background-system bug"
  h1 Bugs
  
  table  class="table table-responsive"
    thead
      tr
        th Title
        th Description
        th Project
        th Status
        th Fix
    tbody
      - @bugs.each do |bug| 
        tr
          th scope="row" = link_to bug.title, bug 
          td = truncate(bug.description, :length => 60, :separator => ' ')
          td = bug.project.name 
          td
            strong =(bug.solved ? "Fixed" : "Not fixed")
          td 
            - if bug.solved == false
                - bug.solved = true
                = link_to "", bug_path(:bug => bug.attributes, :id => bug.id), :method => :put, :class => "glyphicon glyphicon-ok"

  div class= "end-of-content"
    = link_to 'See Projects', projects_path 
  
    = link_to 'Report a Bug', new_bug_path 
  

app/views/bugs/new.html.slim
div.jumbotron.background-system.bug.new_bug

  h1 Report a Bug
  
  = render 'form', bug: @bug 
  div.end-of-content
     = link_to 'Back', request.referrer

app/views/bugs/show.html.slim
div.jumbotron.background-system.bug-show

  h1 = @bug.title.titleize 
  p
    strong Project: 
    = @bug.project.name
  
  p
    strong Description: 
    = @bug.description
  
  p
    strong Status: 
    = (@bug.solved ? "Fixed" : "Not fixed")
  
  div.end-of-content
    = link_to 'Back', bugs_path

app/views/layouts/_error_signup_messages.html.slim
- if object.errors.any?
    div class="alert alert-error-style list-group"    
      p
        strong This form contains #{pluralize(object.errors.count, 'error')}
      ul class="list-errors"
        - object.errors.full_messages.each do |msg| 
          li
            = msg
            
            

app/views/layouts/_flash_messages.html.slim
- flash.each do |name, msg|
	#flash class="alert alert-#{name}"
		= msg 

app/views/layouts/_footer.html.slim
footer.footer
  div class="container"
    small
      ' Developed by Eduardo Fernando Araujo
    nav
      ul
        li = link_to "About",   '#'
        li = link_to "Contact", '#'

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse.menu-bar
  .container 
    #logo = link_to (root_path) do "Inventos Challenge" end
    nav
      ul.nav.nav-bar
        li = link_to "Home",   root_path
        - if user_signed_in?
          li = link_to "Log out",    destroy_user_session_path, method: :delete 
        - else 
          li = link_to "Log in", new_user_session_path

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title #{full_title(yield(:title))}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
    link href="https://fonts.googleapis.com/css?family=Khula:400,700" rel="stylesheet"
  body
    = render 'layouts/header'
    div class="container"
      = render 'layouts/flash_messages'
      = yield
    = render 'layouts/footer'

app/views/projects/_form.html.slim
= semantic_form_for @project do |f|
  - unless @project.errors.empty? 
    = render 'layouts/error_signup_messages', object: @project
  = f.inputs 
    .form-group
      = f.input :name,  :input_html => {:autofocus => true, :class => "form-control" }
    .form-group
      = f.input :project_manager,  :input_html => {:autocomplete => "off", :class => "form-control"}
    .form-group
      = f.input :description, :as => :text, :input_html => {:autocomplete => "off", :class => "form-control"}
    .form-group
      = f.input :area, :collection => [ "Information Technology", "Education", "Finance", "Tourism", "Sales and Marketing"], :input_html => {:autocomplete => "off", :class => "form-control"}, :wrapper_html => { :class => 'fl' }
    .form-group
      = f.input :state, :as => :select, :collection => ["Not started", "In progress", "Completed"], :input_html => {:autocomplete => "off", :class => "form-control margin-left-40"}
    .form-group
      = f.input :date_create, :label => "Start Date", :input_html => {:autocomplete => "off", :class => "form-control"}, :as => :date_picker, :wrapper_html => { :class => 'fl' }
    .form-group
      = f.input :date_finished, :label => "Finish Date",  :input_html => {:autocomplete => "off", :class => "form-control"}, :as => :date_picker

  = f.actions
    = f.action :submit, :as => :input, :button_html => { :disable_with => t(:wait), :class => "btn btn-success btn-block" } 

app/views/projects/edit.html.slim
div class="center jumbotron background-system project project-create"
  h1 Editing Project
  
  = render 'form', project: @project 
  
  div class= "end-of-content"
    = link_to 'Back', projects_path 
    = link_to 'Show', @project  

app/views/projects/index.html.slim
div class=" jumbotron background-system project"

  h1 Projects
  table  class="table" 
    thead 
      tr
        th Name
        th Project Manager 
        th Description
        th Start Date
        th Date Finished
        th Area
        th State
        th Edit
    tbody
      - @projects.each do |project| 
        tr
          th scope="row" = link_to project.name, project 
          td = project.project_manager 
          td = truncate(project.description, :length => 55, :separator => ' ') 
          td = project.date_create
          td = project.date_finished 
          td = project.area 
          td = project.state 
          td 
              = link_to '', edit_project_path(project), :class => "glyphicon glyphicon-pencil"
              = link_to '', project, method: :delete, data: { confirm: 'Are you sure?' },  :class => "glyphicon glyphicon-remove"
    
  div class= "end-of-content"
    = link_to 'New Project', new_project_path
    = link_to 'Bugs List', bugs_path
    = link_to 'Report a Bug', new_bug_path

app/views/projects/new.html.slim
div class="center jumbotron background-system project project-create"
  h1 New Project 
  = render 'form', project: @project 
  div class= "end-of-content"
    = link_to 'Back', projects_path 

app/views/projects/show.html.slim
div class="jumbotron background-system project project-show"

  h3  Project 
  
  h1
    = @project.name.titleize
  
  p
    strong Project manager: 
    = @project.project_manager 
  
  p
    strong Description: 
    = @project.description 
  p
    strong Date create: 
    = @project.date_create

  p
    strong Date finished: 
    = @project.date_finished 

  p
    strong Area: 
    = @project.area 

  p
    strong State: 
    = @project.state 

  div class= "end-of-content"
    = link_to 'Back', projects_path 
    = link_to 'Edit', edit_project_path(@project) 

app/views/static_pages/home.html.slim
div.center.jumbotron.jumboinitial
  h1 Inventos Digitais Challenge
  - if user_signed_in?
      h3
        = "#{current_user.name.titleize},  Welcome  to the System."
      = link_to 'Manage Projects', projects_path, class: "btn btn-lg purple-button"
      = link_to 'See Bug List', bugs_path, class: "btn btn-lg red-button"

  - else
      = link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg purple-button"